"""empty message

Revision ID: bc2e5ccdb415
Revises: ae3ebb785b09
Create Date: 2024-11-07 15:54:32.424710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2e5ccdb415'
down_revision: Union[str, None] = 'ae3ebb785b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_verified')
    # ### end Alembic commands ###
